name: CI
on: [push, pull_request]

env:
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - run: yarn run lint
      - run: yarn workspaces run build
      - run: yarn run test:ci
      - run: yarn generate-docs
