name: Publish Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        type: choice
        description: "Package to publish"
        required: true
        options:
          - assert
          - number-format
          - time-utils
          - regions
          - ui-components

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  PACKAGE_NAME: "@actnowcoalition/${{ github.event.inputs.package_name }}"

jobs:
  publish:
    name: "Publish package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@actnowcoalition"
          cache: yarn
      - run: yarn install
      - run: yarn workspaces run build
      - run: yarn workspace ${{ env.PACKAGE_NAME }} publish --access public
